server:
  port: 7003

# kafka integration is disabled now
enable:
  kafka:
    feature: false

# Netflix Eureka
eureka:
  client:
    healthcheck:
      enabled: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

# General Spring
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  datasource:
    url: "jdbc:mysql://localhost:7000/book_microservice"
    username: root
    password: 123456

# Kafka
kafka:
  topic:
    book:
      events: "book_events"
  bootstrap:
    servers: "localhost:9092"
  properties:
    schema:
      registry:
        url: "http://localhost:8081/"