-- Populate data
begin;

INSERT INTO book_category (id,name) VALUES (0,"Undefined");
INSERT INTO book_category (id,name) VALUES (1,"General");
INSERT INTO book_category (id,name) VALUES (2,"Fantasy");
INSERT INTO book_category (id,name) VALUES (3,"Adventure");
INSERT INTO book_category (id,name) VALUES (4,"Romance");
INSERT INTO book_category (id,name) VALUES (5,"Contemporary");
INSERT INTO book_category (id,name) VALUES (6,"Dystopian");
INSERT INTO book_category (id,name) VALUES (7,"Mystery");
INSERT INTO book_category (id,name) VALUES (8,"Horror");
INSERT INTO book_category (id,name) VALUES (9,"Thriller");
INSERT INTO book_category (id,name) VALUES (10,"Paranormal");
INSERT INTO book_category (id,name) VALUES (11,"Historical fiction");
INSERT INTO book_category (id,name) VALUES (12,"Science Fiction");
INSERT INTO book_category (id,name) VALUES (13,"Memoir");
INSERT INTO book_category (id,name) VALUES (14,"Cooking");
INSERT INTO book_category (id,name) VALUES (15,"Art");
INSERT INTO book_category (id,name) VALUES (16,"Self-help");
INSERT INTO book_category (id,name) VALUES (17,"Development");
INSERT INTO book_category (id,name) VALUES (18,"Motivational");
INSERT INTO book_category (id,name) VALUES (19,"Health");
INSERT INTO book_category (id,name) VALUES (20,"History");
INSERT INTO book_category (id,name) VALUES (21,"Travel");
INSERT INTO book_category (id,name) VALUES (22,"Guide");
INSERT INTO book_category (id,name) VALUES (23,"Families & Relationships");
INSERT INTO book_category (id,name) VALUES (24,"Humor");
INSERT INTO book_category (id,name) VALUES (25,"Children’s");


INSERT INTO author (name) VALUES ('Brown, Dan');
INSERT INTO author (name) VALUES ('Rowling, J.K.');
INSERT INTO author (name) VALUES ('James, E. L.');
INSERT INTO author (name) VALUES ('Meyer, Stephenie');
INSERT INTO author (name) VALUES ('Larsson, Stieg');
INSERT INTO author (name) VALUES ('Sebold, Alice');
INSERT INTO author (name) VALUES ('Haddon, Mark');
INSERT INTO author (name) VALUES ('Bryson, Bill');
INSERT INTO author (name) VALUES ('Carle, Eric');
INSERT INTO author (name) VALUES ('Donaldson, Julia');
INSERT INTO author (name) VALUES ('Oliver, Jamie');
INSERT INTO author (name) VALUES ('Hosseini, Khaled');
INSERT INTO author (name) VALUES ('Nicholls, David');
INSERT INTO author (name) VALUES ('Niffenegger, Audrey');
INSERT INTO author (name) VALUES ('McEwan, Ian');
INSERT INTO author (name) VALUES ('Fielding, Helen');
INSERT INTO author (name) VALUES ('Clarkson, Jeremy');
INSERT INTO author (name) VALUES ('Bernieres, Louis de');
INSERT INTO author (name) VALUES ('Kay, Peter');
INSERT INTO author (name) VALUES ('Martel, Yann');
INSERT INTO author (name) VALUES ('Stephenson, Pamela');
INSERT INTO author (name) VALUES ('Pelzer, Dave');
INSERT INTO author (name) VALUES ('McCourt, Frank');
INSERT INTO author (name) VALUES ('Faulks, Sebastian');
INSERT INTO author (name) VALUES ('Pullman, Philip');
INSERT INTO author (name) VALUES ('Mosse, Kate');
INSERT INTO author (name) VALUES ('Stockett, Kathryn');
INSERT INTO author (name) VALUES ('Parsons, Tony');
INSERT INTO author (name) VALUES ('Golden, Arthur');
INSERT INTO author (name) VALUES ('McCall Smith, Alexander');
INSERT INTO author (name) VALUES ('Hislop, Victoria');
INSERT INTO author (name) VALUES ('Ahern, Cecelia');
INSERT INTO author (name) VALUES ('McKeith, Gillian');
INSERT INTO author (name) VALUES ('Zafon, Carlos Ruiz');
INSERT INTO author (name) VALUES ('Grisham, John');
INSERT INTO author (name) VALUES ('Atkins, Robert C.');
INSERT INTO author (name) VALUES ('Truss, Lynne');
INSERT INTO author (name) VALUES ('Smith, Delia');
INSERT INTO author (name) VALUES ('Harris, Joanne');
INSERT INTO author (name) VALUES ('Boyne, John');
INSERT INTO author (name) VALUES ('Picoult, Jodi');
INSERT INTO author (name) VALUES ('Lee, Harper');
INSERT INTO author (name) VALUES ('Gray, John');
INSERT INTO author (name) VALUES ('French, Dawn');
INSERT INTO author (name) VALUES ('Lewycka, Marina');
INSERT INTO author (name) VALUES ('Harris, Thomas');
INSERT INTO author (name) VALUES ('Tolkien, J. R. R.');
INSERT INTO author (name) VALUES ('Moore, Michael');
INSERT INTO author (name) VALUES ('Rubenfeld, Jed');
INSERT INTO author (name) VALUES ('Osbourne, Sharon');
INSERT INTO author (name) VALUES ('Coelho, Paulo');
INSERT INTO author (name) VALUES ('OGrady, Paul');
INSERT INTO author (name) VALUES ('McKenna, Paul');
INSERT INTO author (name) VALUES ('Levy, Andrea');
INSERT INTO author (name) VALUES ('Lawson, Nigella');
INSERT INTO author (name) VALUES ('Ali, Monica');
INSERT INTO author (name) VALUES ('Edwards, Kim');
INSERT INTO author (name) VALUES ('Hornby, Nick');
INSERT INTO author (name) VALUES ('Brand, Russell');
INSERT INTO author (name) VALUES ('Dawkins, Richard');
INSERT INTO author (name) VALUES ('Smith, Zadie');
INSERT INTO author (name) VALUES ('Morton, Kate');
INSERT INTO author (name) VALUES ('Zusak, Markus');
INSERT INTO author (name) VALUES ('Binchy, Maeve');
INSERT INTO author (name) VALUES ('Harris, Robert');
INSERT INTO author (name) VALUES ('Collins, Suzanne');

INSERT INTO book (name, book_category_id) VALUES ('Da Vinci Code,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Brown, Dan'));
INSERT INTO book (name, book_category_id) VALUES ('Harry Potter and the Deathly Hallows', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Rowling, J.K.'));
INSERT INTO book (name, book_category_id) VALUES ('Harry Potter and the Philosophers Stone', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Rowling, J.K.'));
INSERT INTO book (name, book_category_id) VALUES ('Harry Potter and the Order of the Phoenix', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Rowling, J.K.'));
INSERT INTO book (name, book_category_id) VALUES ('Fifty Shades of Grey', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='James, E. L.'));
INSERT INTO book (name, book_category_id) VALUES ('Harry Potter and the Goblet of Fire', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Rowling, J.K.'));
INSERT INTO book (name, book_category_id) VALUES ('Harry Potter and the Chamber of Secrets', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Rowling, J.K.'));
INSERT INTO book (name, book_category_id) VALUES ('Harry Potter and the Prisoner of Azkaban', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Rowling, J.K.'));
INSERT INTO book (name, book_category_id) VALUES ('Angels and Demons', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Brown, Dan'));
INSERT INTO book (name, book_category_id) VALUES ('Harry Potter and the Half-blood Prince:Childrens Edition', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Rowling, J.K.'));
INSERT INTO book (name, book_category_id) VALUES ('Fifty Shades Darker', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='James, E. L.'));
INSERT INTO book (name, book_category_id) VALUES ('Twilight', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Meyer, Stephenie'));
INSERT INTO book (name, book_category_id) VALUES ('Girl with the Dragon Tattoo,The:Millennium Trilogy', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Larsson, Stieg'));
INSERT INTO book (name, book_category_id) VALUES ('Fifty Shades Freed', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='James, E. L.'));
INSERT INTO book (name, book_category_id) VALUES ('Lost Symbol,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Brown, Dan'));
INSERT INTO book (name, book_category_id) VALUES ('New Moon', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Meyer, Stephenie'));
INSERT INTO book (name, book_category_id) VALUES ('Deception Point', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Brown, Dan'));
INSERT INTO book (name, book_category_id) VALUES ('Eclipse', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Meyer, Stephenie'));
INSERT INTO book (name, book_category_id) VALUES ('Lovely Bones,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Sebold, Alice'));
INSERT INTO book (name, book_category_id) VALUES ('Curious Incident of the Dog in the Night-time,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Haddon, Mark'));
INSERT INTO book (name, book_category_id) VALUES ('Digital Fortress', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Brown, Dan'));
INSERT INTO book (name, book_category_id) VALUES ('Short History of Nearly Everything,A', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Bryson, Bill'));
INSERT INTO book (name, book_category_id) VALUES ('Girl Who Played with Fire,The:Millennium Trilogy', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Larsson, Stieg'));
INSERT INTO book (name, book_category_id) VALUES ('Breaking Dawn', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Meyer, Stephenie'));
INSERT INTO book (name, book_category_id) VALUES ('Very Hungry Caterpillar,The:The Very Hungry Caterpillar', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Carle, Eric'));
INSERT INTO book (name, book_category_id) VALUES ('Gruffalo,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Donaldson, Julia'));
INSERT INTO book (name, book_category_id) VALUES ('Jamies 30-Minute Meals', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Oliver, Jamie'));
INSERT INTO book (name, book_category_id) VALUES ('Kite Runner,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Hosseini, Khaled'));
INSERT INTO book (name, book_category_id) VALUES ('One Day', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Nicholls, David'));
INSERT INTO book (name, book_category_id) VALUES ('Thousand Splendid Suns,A', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Hosseini, Khaled'));
INSERT INTO book (name, book_category_id) VALUES ('Girl Who Kicked the Hornets Nest,The:Millennium Trilogy', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Larsson, Stieg'));
INSERT INTO book (name, book_category_id) VALUES ('Time Travelers Wife,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Niffenegger, Audrey'));
INSERT INTO book (name, book_category_id) VALUES ('Atonement', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='McEwan, Ian'));
INSERT INTO book (name, book_category_id) VALUES ('Bridget Joness Diary:A Novel', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Fielding, Helen'));
INSERT INTO book (name, book_category_id) VALUES ('World According to Clarkson,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Clarkson, Jeremy'));
INSERT INTO book (name, book_category_id) VALUES ('Captain Corellis Mandolin', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Bernieres, Louis de'));
INSERT INTO book (name, book_category_id) VALUES ('Sound of Laughter,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Kay, Peter'));
INSERT INTO book (name, book_category_id) VALUES ('Life of Pi', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Martel, Yann'));
INSERT INTO book (name, book_category_id) VALUES ('Billy Connolly', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Stephenson, Pamela'));
INSERT INTO book (name, book_category_id) VALUES ('Child Called It,A', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Pelzer, Dave'));
INSERT INTO book (name, book_category_id) VALUES ('Gruffalos Child,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Donaldson, Julia'));
INSERT INTO book (name, book_category_id) VALUES ('Angelas Ashes:A Memoir of a Childhood', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='McCourt, Frank'));
INSERT INTO book (name, book_category_id) VALUES ('Birdsong', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Faulks, Sebastian'));
INSERT INTO book (name, book_category_id) VALUES ('Northern Lights:His Dark Materials S.', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Pullman, Philip'));
INSERT INTO book (name, book_category_id) VALUES ('Labyrinth', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Mosse, Kate'));
INSERT INTO book (name, book_category_id) VALUES ('Harry Potter and the Half-blood Prince', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Rowling, J.K.'));
INSERT INTO book (name, book_category_id) VALUES ('Help,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Stockett, Kathryn'));
INSERT INTO book (name, book_category_id) VALUES ('Man and Boy', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Parsons, Tony'));
INSERT INTO book (name, book_category_id) VALUES ('Memoirs of a Geisha', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Golden, Arthur'));
INSERT INTO book (name, book_category_id) VALUES ('No.1 Ladies Detective Agency,The:No.1 Ladies Detective Agency S.', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='McCall Smith, Alexander'));
INSERT INTO book (name, book_category_id) VALUES ('Island,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Hislop, Victoria'));
INSERT INTO book (name, book_category_id) VALUES ('PS, I Love You', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Ahern, Cecelia'));
INSERT INTO book (name, book_category_id) VALUES ('You are What You Eat:The Plan That Will Change Your Life', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='McKeith, Gillian'));
INSERT INTO book (name, book_category_id) VALUES ('Shadow of the Wind,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Zafon, Carlos Ruiz'));
INSERT INTO book (name, book_category_id) VALUES ('Tales of Beedle the Bard,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Rowling, J.K.'));
INSERT INTO book (name, book_category_id) VALUES ('Broker,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Grisham, John'));
INSERT INTO book (name, book_category_id) VALUES ('Dr. Atkins New Diet Revolution:The No-hunger, Luxurious Weight Loss P', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Atkins, Robert C.'));
INSERT INTO book (name, book_category_id) VALUES ('Subtle Knife,The:His Dark Materials S.', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Pullman, Philip'));
INSERT INTO book (name, book_category_id) VALUES ('Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Truss, Lynne'));
INSERT INTO book (name, book_category_id) VALUES ('Delias How to Cook:(Bk.1)', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Smith, Delia'));
INSERT INTO book (name, book_category_id) VALUES ('Chocolat', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Harris, Joanne'));
INSERT INTO book (name, book_category_id) VALUES ('Boy in the Striped Pyjamas,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Boyne, John'));
INSERT INTO book (name, book_category_id) VALUES ('My Sisters Keeper', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Picoult, Jodi'));
INSERT INTO book (name, book_category_id) VALUES ('Amber Spyglass,The:His Dark Materials S.', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Pullman, Philip'));
INSERT INTO book (name, book_category_id) VALUES ('To Kill a Mockingbird', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Lee, Harper'));
INSERT INTO book (name, book_category_id) VALUES ('Men are from Mars, Women are from Venus:A Practical Guide for Improvin', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Gray, John'));
INSERT INTO book (name, book_category_id) VALUES ('Dear Fatty', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='French, Dawn'));
INSERT INTO book (name, book_category_id) VALUES ('Short History of Tractors in Ukrainian,A', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Lewycka, Marina'));
INSERT INTO book (name, book_category_id) VALUES ('Hannibal', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Harris, Thomas'));
INSERT INTO book (name, book_category_id) VALUES ('Lord of the Rings,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Tolkien, J. R. R.'));
INSERT INTO book (name, book_category_id) VALUES ('Stupid White Men:...and Other Sorry Excuses for the State of the Natio', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Moore, Michael'));
INSERT INTO book (name, book_category_id) VALUES ('Interpretation of Murder,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Rubenfeld, Jed'));
INSERT INTO book (name, book_category_id) VALUES ('Sharon Osbourne Extreme:My Autobiography', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Osbourne, Sharon'));
INSERT INTO book (name, book_category_id) VALUES ('Alchemist,The:A Fable About Following Your Dream', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Coelho, Paulo'));
INSERT INTO book (name, book_category_id) VALUES ('At My Mothers Knee ...:and Other Low Joints', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='OGrady, Paul'));
INSERT INTO book (name, book_category_id) VALUES ('Notes from a Small Island', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Bryson, Bill'));
INSERT INTO book (name, book_category_id) VALUES ('Return of the Naked Chef,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Oliver, Jamie'));
INSERT INTO book (name, book_category_id) VALUES ('Bridget Jones: The Edge of Reason', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Fielding, Helen'));
INSERT INTO book (name, book_category_id) VALUES ('Jamies Italy', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Oliver, Jamie'));
INSERT INTO book (name, book_category_id) VALUES ('I Can Make You Thin', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='McKenna, Paul'));
INSERT INTO book (name, book_category_id) VALUES ('Down Under', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Bryson, Bill'));
INSERT INTO book (name, book_category_id) VALUES ('Summons,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Grisham, John'));
INSERT INTO book (name, book_category_id) VALUES ('Small Island', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Levy, Andrea'));
INSERT INTO book (name, book_category_id) VALUES ('Nigella Express', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Lawson, Nigella'));
INSERT INTO book (name, book_category_id) VALUES ('Brick Lane', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Ali, Monica'));
INSERT INTO book (name, book_category_id) VALUES ('Memory Keepers Daughter,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Edwards, Kim'));
INSERT INTO book (name, book_category_id) VALUES ('Room on the Broom', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Donaldson, Julia'));
INSERT INTO book (name, book_category_id) VALUES ('About a Boy', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Hornby, Nick'));
INSERT INTO book (name, book_category_id) VALUES ('My Booky Wook', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Brand, Russell'));
INSERT INTO book (name, book_category_id) VALUES ('God Delusion,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Dawkins, Richard'));
INSERT INTO book (name, book_category_id) VALUES ('White Teeth', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Smith, Zadie'));
INSERT INTO book (name, book_category_id) VALUES ('House at Riverton,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Morton, Kate'));
INSERT INTO book (name, book_category_id) VALUES ('Book Thief,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Zusak, Markus'));
INSERT INTO book (name, book_category_id) VALUES ('Nights of Rain and Stars', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Binchy, Maeve'));
INSERT INTO book (name, book_category_id) VALUES ('Ghost,The', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Harris, Robert'));
INSERT INTO book (name, book_category_id) VALUES ('Happy Days with the Naked Chef', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Oliver, Jamie'));
INSERT INTO book (name, book_category_id) VALUES ('Hunger Games,The:Hunger Games Trilogy', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Collins, Suzanne'));
INSERT INTO book (name, book_category_id) VALUES ('Lost Boy,The:A Foster Childs Search for the Love of a Family', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Pelzer, Dave'));
INSERT INTO book (name, book_category_id) VALUES ('Jamies Ministry of Food:Anyone Can Learn to Cook in 24 Hours', 0);
INSERT INTO book_authors (book_id, author_id) values ((SELECT MAX(ID) FROM book),(SELECT MAX(ID) FROM author WHERE name='Oliver, Jamie'));

commit;

-- //@UNDO
-- SQL to undo the change goes here.
SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE book_authors;
TRUNCATE TABLE book;
TRUNCATE TABLE author;
TRUNCATE TABLE book_category;
SET FOREIGN_KEY_CHECKS=1;